/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Negocio.Cargar2;
import com.sun.awt.AWTUtilities;
import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;


/**
 *
 * @author Karito
 */
public final class Ending extends javax.swing.JFrame {

    public Clip clip;
    double i=70, j=1;
    Cargar2 hilo;
    public Ending() throws LineUnavailableException, IOException, UnsupportedAudioFileException {
        initComponents();
        sonido();       
        iniciar();
    }
    
    public void iniciar(){
        setLocationRelativeTo(null);
        Progreso2.setVisible(false);
        hilo = new Cargar2(getProgreso2());
        hilo.start();
        hilo=null;
    }
    
    public void sonido() throws LineUnavailableException, IOException, UnsupportedAudioFileException {
        BufferedInputStream bis = new BufferedInputStream(getClass().getResourceAsStream("/Recursos/ending.wav"));
        AudioInputStream ais = AudioSystem.getAudioInputStream(bis);
        try {
            clip=AudioSystem.getClip();
            clip.open(ais);                   
            clip.start();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Progreso2 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(680, 382));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Progreso2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Progreso2StateChanged(evt);
            }
        });
        getContentPane().add(Progreso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 280, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ending final.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 382));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Progreso2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Progreso2StateChanged
        // TODO add your handling code here:
        
        if(Progreso2.getValue()==i){
            if(j!=101){
                AWTUtilities.setWindowOpacity(this, Float.valueOf((100-j)/100+"f"));
                i++;
                j+=5;
            }
        }
        
        if(Progreso2.getValue()==100){
            System.exit(0);
        }
    }//GEN-LAST:event_Progreso2StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Ending().setVisible(true);
                } catch (LineUnavailableException ex) {
                    Logger.getLogger(Ending.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Ending.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedAudioFileException ex) {
                    Logger.getLogger(Ending.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Progreso2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the Progreso2
     */
    public javax.swing.JProgressBar getProgreso2() {
        return Progreso2;
    }

    /**
     * @param Progreso2 the Progreso2 to set
     */
    public void setProgreso2(javax.swing.JProgressBar Progreso2) {
        this.Progreso2 = Progreso2;
    }
}
