/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

/**
 *
 * @author Karito
 */



import Negocio.Ecuacion;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;


public class Movimiento extends javax.swing.JFrame {

    
    private Ecuacion myEcuacion;
    
    public Movimiento() {
        initComponents();
        
        setLocationRelativeTo(null);
        this.setResizable(false);
        
        this.myEcuacion = new Ecuacion();

        this.botonGraficar1.setVisible(false);
        this.botonGraficar2.setVisible(false);
        this.botonGraficar3.setVisible(false);
        this.botonGraficar4.setVisible(true);
        
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtM = new javax.swing.JTextField();
        txtC = new javax.swing.JTextField();
        txtK = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextArea();
        botonCalcular = new javax.swing.JButton();
        botonGraficar1 = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonGraficar2 = new javax.swing.JButton();
        botonGraficar3 = new javax.swing.JButton();
        tituloMov = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtInfo = new javax.swing.JLabel();
        txtInfo2 = new javax.swing.JLabel();
        botonGraficar4 = new javax.swing.JButton();
        fondoMov = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(680, 382));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtM.setText("M");
        txtM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMMouseClicked(evt);
            }
        });
        txtM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMActionPerformed(evt);
            }
        });
        getContentPane().add(txtM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 40, 30));

        txtC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtC.setText("C");
        txtC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCMouseClicked(evt);
            }
        });
        getContentPane().add(txtC, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 40, 30));

        txtK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtK.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtK.setText("K");
        txtK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtKMouseClicked(evt);
            }
        });
        txtK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKActionPerformed(evt);
            }
        });
        getContentPane().add(txtK, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 40, 30));

        txtMostrar.setEditable(false);
        txtMostrar.setColumns(20);
        txtMostrar.setRows(5);
        jScrollPane1.setViewportView(txtMostrar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 90, 340, 270));

        botonCalcular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton calcular.png"))); // NOI18N
        botonCalcular.setBorder(null);
        botonCalcular.setBorderPainted(false);
        botonCalcular.setContentAreaFilled(false);
        botonCalcular.setPreferredSize(new java.awt.Dimension(84, 30));
        botonCalcular.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton calcular p.png"))); // NOI18N
        botonCalcular.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton calcular m.png"))); // NOI18N
        botonCalcular.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton calcular m.png"))); // NOI18N
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(botonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 84, 30));

        botonGraficar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonGraficar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton grafica.png"))); // NOI18N
        botonGraficar1.setBorder(null);
        botonGraficar1.setBorderPainted(false);
        botonGraficar1.setContentAreaFilled(false);
        botonGraficar1.setPreferredSize(new java.awt.Dimension(84, 30));
        botonGraficar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton grafica p.png"))); // NOI18N
        botonGraficar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton grafica m.png"))); // NOI18N
        botonGraficar1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton grafica m.png"))); // NOI18N
        botonGraficar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGraficar1MouseClicked(evt);
            }
        });
        getContentPane().add(botonGraficar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 80, -1));

        botonSalir.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton salir.png"))); // NOI18N
        botonSalir.setBorder(null);
        botonSalir.setBorderPainted(false);
        botonSalir.setContentAreaFilled(false);
        botonSalir.setPreferredSize(new java.awt.Dimension(84, 30));
        botonSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton salir p.png"))); // NOI18N
        botonSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton salir m.png"))); // NOI18N
        botonSalir.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton salir m.png"))); // NOI18N
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 80, -1));

        botonGraficar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton grafica.png"))); // NOI18N
        botonGraficar2.setBorder(null);
        botonGraficar2.setBorderPainted(false);
        botonGraficar2.setContentAreaFilled(false);
        botonGraficar2.setPreferredSize(new java.awt.Dimension(84, 30));
        botonGraficar2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton grafica p.png"))); // NOI18N
        botonGraficar2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton grafica m.png"))); // NOI18N
        botonGraficar2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton grafica m.png"))); // NOI18N
        botonGraficar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGraficar2MouseClicked(evt);
            }
        });
        getContentPane().add(botonGraficar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 80, -1));

        botonGraficar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton grafica.png"))); // NOI18N
        botonGraficar3.setBorder(null);
        botonGraficar3.setBorderPainted(false);
        botonGraficar3.setContentAreaFilled(false);
        botonGraficar3.setPreferredSize(new java.awt.Dimension(84, 30));
        botonGraficar3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton grafica p.png"))); // NOI18N
        botonGraficar3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton grafica m.png"))); // NOI18N
        botonGraficar3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton grafica m.png"))); // NOI18N
        botonGraficar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGraficar3MouseClicked(evt);
            }
        });
        getContentPane().add(botonGraficar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 80, -1));

        tituloMov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/título-2.png"))); // NOI18N
        getContentPane().add(tituloMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 620, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("  X\" +        X' +        X = 0");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 230, 30));

        txtInfo.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        txtInfo.setText("NT. Las variables corresponden a:");
        getContentPane().add(txtInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 200, 30));

        txtInfo2.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        txtInfo2.setText("M = Masa, C = Cte Amortiguamiento, K = Rigidez");
        getContentPane().add(txtInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 320, -1));

        botonGraficar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton grafica.png"))); // NOI18N
        botonGraficar4.setBorder(null);
        botonGraficar4.setBorderPainted(false);
        botonGraficar4.setContentAreaFilled(false);
        botonGraficar4.setPreferredSize(new java.awt.Dimension(84, 30));
        botonGraficar4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton grafica p.png"))); // NOI18N
        botonGraficar4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton grafica m.png"))); // NOI18N
        botonGraficar4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton grafica m.png"))); // NOI18N
        getContentPane().add(botonGraficar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        fondoMov.setBackground(new java.awt.Color(0, 0, 0));
        fondoMov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondo3.jpg"))); // NOI18N
        getContentPane().add(fondoMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 382));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKActionPerformed

    private void txtMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMActionPerformed

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        // TODO add your handling code here:
        String masa = this.txtM.getText();
        String cte = this.txtC.getText();
        String rigidez = this.txtK.getText();
                   
        if (masa.isEmpty() || cte.isEmpty() || rigidez.isEmpty()) {
            Ventana.imp(" Falta Digitar Datos ", " SISTEMA ");
            return;
        }
        
        int m= Integer.parseInt(masa);
        int c= Integer.parseInt(cte);
        int k= Integer.parseInt(rigidez);
        String cad = this.myEcuacion.calcular(m,c,k);
        
        this.txtMostrar.setText(cad);
        
        
        int a = (int) Math.pow(c, 2);
        int b = a - ((4 * m) * k);
        int d = 2 * m;
        String r1,r2;
        

        if (b < 0) {
            int aux1 = -c / d;            
            int imag1 = ((int) Math.sqrt(b * (-1))) / d;
            r1 = aux1 + " + " + imag1 + "i";
            
        } else {
            int raiz = (-c + (int) Math.sqrt(b)) / d;
            r1 = "" + raiz;
        }
        
        if (b < 0) {
            int aux2 = -c / d;
            int imag2 = ((int) Math.sqrt(b * (-1))) / d;
            r2 = aux2 + " - " + imag2 + "i";
            
        } else {
            int raiz2 = (-c - (int) Math.sqrt(b)) / d;
            r2 = "" + raiz2;
        }
        
        if (b < 0) {
            this.botonGraficar1.setVisible(true);
            this.botonGraficar4.setVisible(false);
        } else {
            if (r1.equals(r2)) {
                this.botonGraficar2.setVisible(true);
                this.botonGraficar4.setVisible(false);
            } else {
                this.botonGraficar3.setVisible(true);
                this.botonGraficar4.setVisible(false);
            }
            
        }
    }//GEN-LAST:event_botonCalcularActionPerformed

    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseClicked
        try {
            // TODO add your handling code here:
            Ending e = new Ending();
            e.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(Movimiento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(Movimiento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(Movimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonSalirMouseClicked

    private void txtMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMMouseClicked
        // TODO add your handling code here:
        limpiarM();
    }//GEN-LAST:event_txtMMouseClicked

    private void txtCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCMouseClicked
        // TODO add your handling code here:
        limpiarC();
    }//GEN-LAST:event_txtCMouseClicked

    private void txtKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKMouseClicked
        // TODO add your handling code here:
        limpiarK();
    }//GEN-LAST:event_txtKMouseClicked

    private void botonGraficar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGraficar1MouseClicked
        // TODO add your handling code here:
        Graficador1 grafico = new Graficador1();
        grafico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonGraficar1MouseClicked

    private void botonGraficar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGraficar2MouseClicked
        // TODO add your handling code here:
        Graficador2 grafico = new Graficador2();
        grafico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonGraficar2MouseClicked

    private void botonGraficar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGraficar3MouseClicked
        // TODO add your handling code here:
        Graficador3 grafico = new Graficador3();
        grafico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonGraficar3MouseClicked

    private void limpiarM() {
        
        txtM.setText("");
    }

    private void limpiarC() {
        
        txtC.setText("");
    }

    private void limpiarK() {
        
        txtK.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Movimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Movimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Movimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Movimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Movimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcular;
    private javax.swing.JButton botonGraficar1;
    private javax.swing.JButton botonGraficar2;
    private javax.swing.JButton botonGraficar3;
    private javax.swing.JButton botonGraficar4;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel fondoMov;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tituloMov;
    private javax.swing.JTextField txtC;
    private javax.swing.JLabel txtInfo;
    private javax.swing.JLabel txtInfo2;
    private javax.swing.JTextField txtK;
    private javax.swing.JTextField txtM;
    private javax.swing.JTextArea txtMostrar;
    // End of variables declaration//GEN-END:variables
}
